---
deployment:
  tasks:
    - source /home/thenort2/nodevenv/repositories/pict-digital-staging/22/bin/activate && cd /home/thenort2/repositories/pict-digital-staging
    - npm install
    - npm run build
    - cp -r dist/. /home/thenort2/public_html
